---
title: "Resume"
output: html_document
hidedate: true
hiderelated: true
hidediscus: true
---

Kaitlyn Richardson

918-760-1909

kkr647@utexas.edu
 
CAREER OBJECTIVE

Hard-working and eager biology student. Interested in gaining more experience in the healthcare setting. Aiming to leverage skills to become a physician assistant. Special interest in cultural topics of public health, emerging infectious diseases, and genetic disorders.
 
PROFESSIONAL EXPERIENCE 	

THE UNIVERSITY OF TEXAS AUSTIN COLLEGE OF BIOSCIENCES Austin, TX
Undergraduate Genetics TA for Janice Fischer, Aug 2020 – Dec 2020
 	Aid in student learning, prepare class topics, grade class activities, provide tutoring in a classroom setting.
 	Selected based on merit

THE UNVIERSITY OF TEXAS AT AUSTIN COVID-19 CONSORTIUM- Austin, TX
Research Volunteer- Seasonality of COVID-19 with Spencer Fox, September 2020- present
•	Group of student researchers with PI aiming to understand the seasonality of respiratory viruses, focusing on the emergence factors of COVID-19
•	R modeling
•	Selected based on merit

BRIAN SEDIO LAB, Austin, TX
Work Study Research Assistant, Jan 2020 – Sept 2020
•	Bioassays
•	Biostatistical analysis
•	Reagent preparations
•	Aseptic lab techniques
•	Q-PCR
 
SOUTH TEXAS COLLEGE CENTER FOR EXCELLENCE, McAllen , TX
  Tutor, Aug 2018 - Aug 2019 
 	Provide private instruction to individual or small groups of students to improve academic performance,         improve occupational skills, or prepare for academic or occupational tests.
 
USDA WESLACO CITRUS CENTER, Weslaco, TX
Summer Research Intern, May 2019 - Jul 2019 
 	Analyze experimental data and interpret results to write reports and summaries of findings.
 	Keep detailed logs of all work-related activities.
 	Conduct standardized biological, microbiological or biochemical tests and laboratory analyses to evaluate the quantity or quality of physical or chemical substances in plant sources.
 
EDUCATION 	

THE UNIVERSITY OF TEXAS AT AUSTIN
Austin, TX
B.S.A Biology with Pre-Health certificate (Expected graduation Dec 2021)
 	GPA: 3.83
 	Relevant Coursework: Biostats, Genetics, Computational Biology, Microbiology, Anatomy, Cell Biology
 	Awards & Honors: Alpha Lambda Delta and Phi Eta Sigma Society
 	Extracurricular Activities: Valley Horns Member, Synapse Member, Mask’Em creator, PLUS facilitator, COVID Consortium Volunteer
 
SOUTH TEXAS COLLEGE

Mcallen, TX
A.S. Interdisciplinary Studies (May 2018)
 	GPA: 4.0
 	Relevant Coursework: Biology II, Gen Chem I, Gen Chem II, Organic Chem I
 	Awards & Honors: Deans honors 
 	Extracurricular Activities: Biology Club member, Sea Turtle Inc. Volunteer, National Butterfly Center Volunteer 

TULSA COMMUNITY COLLEE

  Tulsa, OK
  Completed coursework towards     A.S. Interdisciplinary Studies     (Dec 2017)
 	GPA: 4.0
 	Relevant Coursework: Bio I,Geology
 	Awards & Honors: Deans honor roll
  
ADDITIONAL SKILLS 

 	Spanish- Fluent
 	PCR and Electrophoresis Experience
 	Experience in R
 	Aseptic Lab Technique
 	Microsoft and Excel Experience
 	Receptionist Experience
 
CREDENTIALS AND LICENSES

 	TEFL Cambridge Institute Certified
 	BLS Certified
 
REFERENCES

DR. KHALID SALMANI, Professor, South Texas College
kmirza@southtexascollege.edu - Former chemistry professor 
DR. JANICE FISCHER, Professor, The University of Texas at Austin
janicefischer@austin.utexas.edu - Genetics Professor
DR. DAN MURRAY, USDA Mentor and Professor, South Texas College
kdmurray@southtexascollege.edu - USDA mentor
ISSAC GARZA, Coordinator of the Center of Excellence- South Texas College, Center of Excellence South Texas College
rgarza_0843@southtexascollege.edu - Supervisor 




